apiVersion : apps/v1
kind: Deployment
metadata:
  name: sampleapp 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp 
    spec:
      containers:
        - name: sampleapp 
          image: myk8cr.azurecr.io/sampleapp:latest
          ports:
          - containerPort: 5000


#service type Loadbalancer
apiVersion: v1
kind: Service
metadata:
    name: sampleapp
spec:
  selector:
        app: sampleapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer